.echo on
.mode column
.headers on
.nullvalue NULL

-- VAERSDATA.CSV
DROP TABLE IF EXISTS "1990VAERSDATA";
CREATE TABLE IF NOT EXISTS "1990VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1990VAERSDATA.csv "1990VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1991VAERSDATA";
CREATE TABLE IF NOT EXISTS "1991VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1991VAERSDATA.csv "1991VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1992VAERSDATA";
CREATE TABLE IF NOT EXISTS "1992VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1992VAERSDATA.csv "1992VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1993VAERSDATA";
CREATE TABLE IF NOT EXISTS "1993VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1993VAERSDATA.csv "1993VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1994VAERSDATA";
CREATE TABLE IF NOT EXISTS "1994VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1994VAERSDATA.csv "1994VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1995VAERSDATA";
CREATE TABLE IF NOT EXISTS "1995VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1995VAERSDATA.csv "1995VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1996VAERSDATA";
CREATE TABLE IF NOT EXISTS "1996VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1996VAERSDATA.csv "1996VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1997VAERSDATA";
CREATE TABLE IF NOT EXISTS "1997VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1997VAERSDATA.csv "1997VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1998VAERSDATA";
CREATE TABLE IF NOT EXISTS "1998VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1998VAERSDATA.csv "1998VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "1999VAERSDATA";
CREATE TABLE IF NOT EXISTS "1999VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\1999VAERSDATA.csv "1999VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2000VAERSDATA";
CREATE TABLE IF NOT EXISTS "2000VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2000VAERSDATA.csv "2000VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2001VAERSDATA";
CREATE TABLE IF NOT EXISTS "2001VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2001VAERSDATA.csv "2001VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2002VAERSDATA";
CREATE TABLE IF NOT EXISTS "2002VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2002VAERSDATA.csv "2002VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2003VAERSDATA";
CREATE TABLE IF NOT EXISTS "2003VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2003VAERSDATA.csv "2003VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2004VAERSDATA";
CREATE TABLE IF NOT EXISTS "2004VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2004VAERSDATA.csv "2004VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2005VAERSDATA";
CREATE TABLE IF NOT EXISTS "2005VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2005VAERSDATA.csv "2005VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2006VAERSDATA";
CREATE TABLE IF NOT EXISTS "2006VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2006VAERSDATA.csv "2006VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2007VAERSDATA";
CREATE TABLE IF NOT EXISTS "2007VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2007VAERSDATA.csv "2007VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2008VAERSDATA";
CREATE TABLE IF NOT EXISTS "2008VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2008VAERSDATA.csv "2008VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2009VAERSDATA";
CREATE TABLE IF NOT EXISTS "2009VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2009VAERSDATA.csv "2009VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2010VAERSDATA";
CREATE TABLE IF NOT EXISTS "2010VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2010VAERSDATA.csv "2010VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2011VAERSDATA";
CREATE TABLE IF NOT EXISTS "2011VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2011VAERSDATA.csv "2011VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2012VAERSDATA";
CREATE TABLE IF NOT EXISTS "2012VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2012VAERSDATA.csv "2012VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2013VAERSDATA";
CREATE TABLE IF NOT EXISTS "2013VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2013VAERSDATA.csv "2013VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2014VAERSDATA";
CREATE TABLE IF NOT EXISTS "2014VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2014VAERSDATA.csv "2014VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2015VAERSDATA";
CREATE TABLE IF NOT EXISTS "2015VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2015VAERSDATA.csv "2015VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2016VAERSDATA";
CREATE TABLE IF NOT EXISTS "2016VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2016VAERSDATA.csv "2016VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2017VAERSDATA";
CREATE TABLE IF NOT EXISTS "2017VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2017VAERSDATA.csv "2017VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2018VAERSDATA";
CREATE TABLE IF NOT EXISTS "2018VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2018VAERSDATA.csv "2018VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2019VAERSDATA";
CREATE TABLE IF NOT EXISTS "2019VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2019VAERSDATA.csv "2019VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2020VAERSDATA";
CREATE TABLE IF NOT EXISTS "2020VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2020VAERSDATA.csv "2020VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2021VAERSDATA";
CREATE TABLE IF NOT EXISTS "2021VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2021VAERSDATA.csv "2021VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2022VAERSDATA";
CREATE TABLE IF NOT EXISTS "2022VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2022VAERSDATA.csv "2022VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2023VAERSDATA";
CREATE TABLE IF NOT EXISTS "2023VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2023VAERSDATA.csv "2023VAERSDATA" --csv --skip 1

DROP TABLE IF EXISTS "2024VAERSDATA";
CREATE TABLE IF NOT EXISTS "2024VAERSDATA" (
	VAERS_ID	TEXT	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		TEXT,
	CAGE_YR		TEXT,
	CAGE_MO		TEXT,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	TEXT,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		TEXT,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	TEXT,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
.import csv\2024VAERSDATA.csv "2024VAERSDATA" --csv --skip 1

-- VAERSDATA
DROP TABLE IF EXISTS VAERSDATA;
CREATE TABLE IF NOT EXISTS VAERSDATA (
	VAERS_ID	INTEGER	PRIMARY KEY,
	RECVDATE	TEXT,
	STATE		TEXT,
	AGE_YRS		REAL,
	CAGE_YR		INTEGER,
	CAGE_MO		REAL,
	SEX		TEXT,
	RPT_DATE	TEXT,
	SYMPTOM_TEXT	TEXT,
	DIED		TEXT,
	DATEDIED	TEXT,
	L_THREAT	TEXT,
	ER_VISIT	TEXT,
	HOSPITAL	TEXT,
	HOSPDAYS	INTEGER,
	X_STAY		TEXT,
	DISABLE		TEXT,
	RECOVD		TEXT,
	VAX_DATE	TEXT,
	ONSET_DATE	TEXT,
	NUMDAYS		INTEGER,
	LAB_DATA	TEXT,
	V_ADMINBY	TEXT,
	V_FUNDBY	TEXT,
	OTHER_MEDS	TEXT,
	CUR_ILL		TEXT,
	HISTORY		TEXT,
	PRIOR_VAX	TEXT,
	SPLTTYPE	TEXT,
	FORM_VERS	INTEGER,
	TODAYS_DATE	TEXT,
	BIRTH_DEFECT	TEXT,
	OFC_VISIT	TEXT,
	ER_ED_VISIT	TEXT,
	ALLERGIES 	TEXT
) WITHOUT ROWID;
INSERT INTO VAERSDATA SELECT * FROM "1990VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1991VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1992VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1993VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1994VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1995VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1996VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1997VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1998VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "1999VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2000VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2001VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2002VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2003VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2004VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2005VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2006VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2007VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2008VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2009VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2010VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2011VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2012VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2013VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2014VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2015VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2016VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2017VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2018VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2019VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2020VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2021VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2022VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2023VAERSDATA";
INSERT INTO VAERSDATA SELECT * FROM "2024VAERSDATA";

-- VAERSVAX.CSV
DROP TABLE IF EXISTS "1990VAERSVAX";
CREATE TABLE IF NOT EXISTS "1990VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1990VAERSVAX.csv "1990VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1991VAERSVAX";
CREATE TABLE IF NOT EXISTS "1991VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1991VAERSVAX.csv "1991VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1992VAERSVAX";
CREATE TABLE IF NOT EXISTS "1992VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1992VAERSVAX.csv "1992VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1993VAERSVAX";
CREATE TABLE IF NOT EXISTS "1993VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1993VAERSVAX.csv "1993AERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1994VAERSVAX";
CREATE TABLE IF NOT EXISTS "1994VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1994VAERSVAX.csv "1994VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1995VAERSVAX";
CREATE TABLE IF NOT EXISTS "1995VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1995VAERSVAX.csv "1995VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1996VAERSVAX";
CREATE TABLE IF NOT EXISTS "1996VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1996VAERSVAX.csv "1996VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1997VAERSVAX";
CREATE TABLE IF NOT EXISTS "1997VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1997VAERSVAX.csv "1997VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1998VAERSVAX";
CREATE TABLE IF NOT EXISTS "1998VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1998VAERSVAX.csv "1998VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "1999VAERSVAX";
CREATE TABLE IF NOT EXISTS "1999VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\1999VAERSVAX.csv "1999VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2000VAERSVAX";
CREATE TABLE IF NOT EXISTS "2000VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2000VAERSVAX.csv "2000VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2001VAERSVAX";
CREATE TABLE IF NOT EXISTS "2001VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2001VAERSVAX.csv "2001VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2002VAERSVAX";
CREATE TABLE IF NOT EXISTS "2002VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2002VAERSVAX.csv "2002VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2003VAERSVAX";
CREATE TABLE IF NOT EXISTS "2003VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2003VAERSVAX.csv "2003VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2004VAERSVAX";
CREATE TABLE IF NOT EXISTS "2004VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2004VAERSVAX.csv "2004VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2005VAERSVAX";
CREATE TABLE IF NOT EXISTS "2005VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2005VAERSVAX.csv "2005VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2006VAERSVAX";
CREATE TABLE IF NOT EXISTS "2006VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2006VAERSVAX.csv "2006VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2007VAERSVAX";
CREATE TABLE IF NOT EXISTS "2007VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2007VAERSVAX.csv "2007VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2008VAERSVAX";
CREATE TABLE IF NOT EXISTS "2008VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2008VAERSVAX.csv "2008VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2009VAERSVAX";
CREATE TABLE IF NOT EXISTS "2009VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2009VAERSVAX.csv "2009VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2010VAERSVAX";
CREATE TABLE IF NOT EXISTS "2010VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2010VAERSVAX.csv "2010VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2011VAERSVAX";
CREATE TABLE IF NOT EXISTS "2011VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2011VAERSVAX.csv "2011VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2012VAERSVAX";
CREATE TABLE IF NOT EXISTS "2012VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2012VAERSVAX.csv "2012VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2013VAERSVAX";
CREATE TABLE IF NOT EXISTS "2013VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2013VAERSVAX.csv "2013VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2014VAERSVAX";
CREATE TABLE IF NOT EXISTS "2014VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2014VAERSVAX.csv "2014VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2015VAERSVAX";
CREATE TABLE IF NOT EXISTS "2015VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2015VAERSVAX.csv "2015VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2016VAERSVAX";
CREATE TABLE IF NOT EXISTS "2016VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2016VAERSVAX.csv "2016VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2017VAERSVAX";
CREATE TABLE IF NOT EXISTS "2017VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2017VAERSVAX.csv "2017VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2018VAERSVAX";
CREATE TABLE IF NOT EXISTS "2018VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2018VAERSVAX.csv "2018VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2019VAERSVAX";
CREATE TABLE IF NOT EXISTS "2019VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2019VAERSVAX.csv "2019VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2020VAERSVAX";
CREATE TABLE IF NOT EXISTS "2020VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2020VAERSVAX.csv "2020VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2021VAERSVAX";
CREATE TABLE IF NOT EXISTS "2021VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2021VAERSVAX.csv "2021VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2022VAERSVAX";
CREATE TABLE IF NOT EXISTS "2022VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2022VAERSVAX.csv "2022VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2023VAERSVAX";
CREATE TABLE IF NOT EXISTS "2023VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2023VAERSVAX.csv "2023VAERSVAX" --csv --skip 1

DROP TABLE IF EXISTS "2024VAERSVAX";
CREATE TABLE IF NOT EXISTS "2024VAERSVAX" (
	VAERS_ID	TEXT,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
.import csv\2024VAERSVAX.csv "2024VAERSVAX" --csv --skip 1

-- VAERSVAX
DROP TABLE IF EXISTS VAERSVAX;
CREATE TABLE IF NOT EXISTS VAERSVAX (
	VAERS_ID	INTEGER,
	VAX_TYPE	TEXT,
	VAX_MANU	TEXT,
	VAX_LOT		TEXT,
	VAX_DOSE_SERIES	TEXT,
	VAX_ROUTE	TEXT,
	VAX_SITE	TEXT,
	VAX_NAME	TEXT
);
INSERT INTO VAERSVAX SELECT * FROM "1990VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1991VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1992VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1993VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1994VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1995VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1996VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1997VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1998VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "1999VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2000VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2001VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2002VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2003VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2004VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2005VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2006VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2007VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2008VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2009VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2010VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2011VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2012VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2013VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2014VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2015VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2016VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2017VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2018VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2019VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2020VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2021VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2022VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2023VAERSVAX";
INSERT INTO VAERSVAX SELECT * FROM "2024VAERSVAX";

-- VAERSSYMPTOMS.CSV
DROP TABLE IF EXISTS "1990VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1990VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1990VAERSSYMPTOMS.csv "1990VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1991VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1991VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1991VAERSSYMPTOMS.csv "1991VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1992VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1992VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1992VAERSSYMPTOMS.csv "1992VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1993VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1993VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1993VAERSSYMPTOMS.csv "1993VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1994VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1994VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1994VAERSSYMPTOMS.csv "1994VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1995VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1995VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1995VAERSSYMPTOMS.csv "1995AERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1996VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1996VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1996VAERSSYMPTOMS.csv "1996VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1997VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1997VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1997VAERSSYMPTOMS.csv "1997VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1998VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1998VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1998VAERSSYMPTOMS.csv "1998VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "1999VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "1999VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\1999VAERSSYMPTOMS.csv "1999VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2000VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2000VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2000VAERSSYMPTOMS.csv "2000VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2001VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2001VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2001VAERSSYMPTOMS.csv "2001VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2002VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2002VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2002VAERSSYMPTOMS.csv "2002VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2003VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2003VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2003VAERSSYMPTOMS.csv "2003VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2004VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2004VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2004VAERSSYMPTOMS.csv "2004VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2005VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2005VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2005VAERSSYMPTOMS.csv "2005VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2006VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2006VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2006VAERSSYMPTOMS.csv "2006VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2007VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2007VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2007VAERSSYMPTOMS.csv "2007VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2008VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2008VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2008VAERSSYMPTOMS.csv "2008VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2009VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2009VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2009VAERSSYMPTOMS.csv "2009VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2010VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2010VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2010VAERSSYMPTOMS.csv "2010VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2011VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2011VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2011VAERSSYMPTOMS.csv "2011VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2012VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2012VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2012VAERSSYMPTOMS.csv "2012VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2013VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2013VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2013VAERSSYMPTOMS.csv "2013VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2014VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2014VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2014VAERSSYMPTOMS.csv "2014VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2015VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2015VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2015VAERSSYMPTOMS.csv "2015VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2016VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2016VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2016VAERSSYMPTOMS.csv "2016VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2017VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2017VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2017VAERSSYMPTOMS.csv "2017VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2018VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2018VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2018VAERSSYMPTOMS.csv "2018VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2019VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2019VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2019VAERSSYMPTOMS.csv "2019VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2020VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2020VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2020VAERSSYMPTOMS.csv "2020VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2021VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2021VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2021VAERSSYMPTOMS.csv "2021VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2022VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2022VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2022VAERSSYMPTOMS.csv "2022VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2023VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2023VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2023VAERSSYMPTOMS.csv "2023VAERSSYMPTOMS" --csv --skip 1

DROP TABLE IF EXISTS "2024VAERSSYMPTOMS";
CREATE TABLE IF NOT EXISTS "2024VAERSSYMPTOMS" (
	VAERS_ID	TEXT,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	TEXT,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	TEXT,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	TEXT,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	TEXT,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	TEXT
);
.import csv\2024VAERSSYMPTOMS.csv "2024VAERSSYMPTOMS" --csv --skip 1

-- VAERSSYMPTOMS
DROP TABLE IF EXISTS VAERSSYMPTOMS;
CREATE TABLE IF NOT EXISTS VAERSSYMPTOMS (
	VAERS_ID	INTEGER,
	SYMPTOM1	TEXT,
	SYMPTOMVERSION1	REAL,
	SYMPTOM2	TEXT,
	SYMPTOMVERSION2	REAL,
	SYMPTOM3	TEXT,
	SYMPTOMVERSION3	REAL,
	SYMPTOM4	TEXT,
	SYMPTOMVERSION4	REAL,
	SYMPTOM5	TEXT,
	SYMPTOMVERSION5	REAL
);
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1990VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1991VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1992VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1993VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1994VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1995VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1996VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1997VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1998VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "1999VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2000VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2001VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2002VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2003VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2004VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2005VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2006VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2007VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2008VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2009VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2010VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2011VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2012VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2013VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2014VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2015VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2016VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2017VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2018VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2019VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2020VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2021VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2022VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2023VAERSSYMPTOMS";
INSERT INTO VAERSSYMPTOMS SELECT * FROM "2024VAERSSYMPTOMS";

SELECT COUNT(*) FROM VAERSDATA;
SELECT COUNT(*) FROM VAERSVAX;
SELECT COUNT(*) FROM VAERSSYMPTOMS;
